#!/bin/bash

## Creating main directories for the project
  
# temporary dirrectory
mkdir -p /home/avasileva/temp

# programs direcrory 
mkdir -p /home/avasileva/programs

# project directory
mkdir -p /home/avasileva/project
