#!/bin/bash

mkdir -p /home/avasileva/programs
cd /home/avasileva/programs

sudo apt-get install bedtools
sudo apt-get install bedops
sudo apt-get install parallel

wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip
unzip snpEff_latest_core.zip
